### ISSUE TITLE
Bug: email freaks out when end time is undefined

### ISSUE THREAD

**Issue by MatthewStanciu** [purduehackers/events#42]
<img width="996" alt="Screen Shot 2022-09-22 at 2 29 07 PM" src="https://user-images.githubusercontent.com/14811170/191823972-62d6a50f-ae67-4be6-be38-1a10ef40ec44.png">

Should better handle this. The API route that calls this email sends the data over, so it should send some kind of default value (like `???`).

**Comment by chi-wei-lien** [comment]
yea. totally agree. I don't really know how issues work... If I want to help solve this issue do I create a separate branch and fix it there and create a pull request afterward?

**Comment by chi-wei-lien** [comment]
btw, I noticed that we don't have all the API keys stored in .env since it is not pushed to the repo. Should we have a private repo for all the .env files of all of our projects (probably not the best way...)

**Comment by MatthewStanciu** [comment]
@chi-wei-lien Let's use Vercel as our source of truth, since that's where our projects are ultimately hosted. You can use Vercel CLI to pull environment variables to a local `.env` file. Just go to the folder on your computer where the code for this repo is stored, run `vc link` to link your folder to our Vercel project, then run `vc env pull --environment=production` to pull production environment variables. Happy to help in Discord if you need it.

Re fixing: you got it! Just create a separate branch, then create a pull request from that branch.
